# Generated by Django 5.0.6 on 2024-06-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='about',
            field=models.TextField(verbose_name='about'),
        ),
    ]
