# Generated by Django 5.0.6 on 2024-06-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productbrandmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Brend')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategoriya')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Rang')),
                ('color_code', models.CharField(max_length=255, verbose_name='Rang nomi inglizcha yoki kod (#000)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Teg')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productcommentmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcommentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='productimagemodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='tags',
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner sarlavhasi')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Banner sub sarlavhasi')),
                ('text', models.CharField(max_length=255, verbose_name='Banner Text')),
                ('image', models.ImageField(upload_to='banner/%y/%m/%d/', verbose_name='Banner rasmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('cost', models.FloatField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('base_count', models.IntegerField(default=1, verbose_name='Bazadagi soni')),
                ('description', models.TextField()),
                ('rating_count', models.IntegerField(default=0)),
                ('poster', models.ImageField(upload_to='posters/%y/%m/%d/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('images', models.ManyToManyField(to='products.productimage')),
                ('tag', models.ManyToManyField(to='products.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('review', models.TextField(max_length=355)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner sarlavhasi')),
                ('image', models.ImageField(upload_to='banner/%y/%m/%d/', verbose_name='Banner rasmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductBrandModel',
        ),
        migrations.DeleteModel(
            name='ProductCategoryModel',
        ),
        migrations.DeleteModel(
            name='ProductColorModel',
        ),
        migrations.DeleteModel(
            name='ProductCommentModel',
        ),
        migrations.DeleteModel(
            name='ProductDimensionModel',
        ),
        migrations.DeleteModel(
            name='ProductImageModel',
        ),
        migrations.DeleteModel(
            name='ProductSizeModel',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='ProductTagModel',
        ),
    ]
