# Generated by Django 5.0.6 on 2024-06-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productbrandmodel_productcategorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description',
            field=models.TextField(default='wertyui'),
            preserve_default=False,
        ),
    ]
